In [21]:

import numpy as np
arr=np.random.randint(-15,15,size=(4,4))
print(arr)
print(np.add.reduce(arr))
print(np.logical_and.reduce(arr))

print(np.subtract.accumulate(arr))

[[  9 -15   2   6]
 [  3  -5  -9  -2]
 [  3 -11  -1   1]
 [  7  -7 -11   2]]
[ 22 -38 -19   7]
[ True  True  True  True]
[[  9 -15   2   6]
 [  6 -10  11   8]
 [  3   1  12   7]
 [ -4   8  23   5]]


In [29]:
arr=np.arange(5)
print(arr)
index=np.array([1,4])
np.add.reduceat(arr,index)


[0 1 2 3 4]


array([6, 4])

In [4]:
arr2=np.arange(1,21).reshape(4,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [32]:
arr=np.array([1,2,3,4])
arr1=np.array([1,2,3])
print(np.add.outer(arr,arr1))
print(np.subtract.outer(arr,arr1))

[[2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]]
[[ 0 -1 -2]
 [ 1  0 -1]
 [ 2  1  0]
 [ 3  2  1]]


In [35]:
# Given an array of integers representing daily sales for a week, use np.add.reduce to find the total sales for the entire week.
arr=np.random.randint(1000,5000,size=7)
arr
print(np.add.reduce(arr))

20916


In [ ]:
arr1=np.zeros(10,dtype=int)
print(arr1)
arr2=np.ones(10,dtype=float)*5
print(arr2)
arr3=np.concatenate([arr2,arr1])
print(arr3)
arr4=np.identity(4,dtype=int)
print(arr4)
arr5=np.empty(9,dtype=int)
print(arr5)

[0 0 0 0 0 0 0 0 0 0]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[94602265225506              0              0              0
              0              0              0              0
              0]


In [ ]:
arr2=np.array([1,123,4,5,3,6,7,5])
print(arr2)
print(np.mean(arr2,axis=0))
print(np.median(arr2,axis=0))
print(np.std(arr2,axis=0))
print(np.var(arr2,axis=0))
print(np.min(arr2,axis=0))
print(np.max(arr2,axis=0))
print(np.argmin(arr2,axis=0))
print(np.argmax(arr2,axis=0))
print(np.sort(arr2,axis=0))
print(np.argsort(arr2,axis=0))
print(np.where(arr2==5,arr2,0))
print(np.count_nonzero(arr2))

[  1 123   4   5   3   6   7   5]
19.25
5.0
39.251592324388575
1540.6875
1
123
0
1
[  1   3   4   5   5   6   7 123]
[0 4 2 3 7 5 6 1]
[0 0 0 5 0 0 0 5]
8


In [ ]:
import numpy as np
arr1=np.arange(10.0,30.0,3.5)
print(arr1)
print(arr1.dtype)

