In [3]:
import numpy as np

In [20]:
#Problem 1 : Create 1D array
arr1d=np.array([1,2,3,4,5,6,7,8,9])
print(arr1d)
arr1d.ndim

[1 2 3 4 5 6 7 8 9]


1

In [43]:
#Problem 2 : Create 2D array with dimention (2,3)
arr2d=np.array([[0,0,0],[0,0,0]])
print(arr2d)
arr2d.ndim

[[0 0 0]
 [0 0 0]]


2

In [42]:
#Problem 3 : Create 3D array with dimention (4,2,3)
arr3d=np.array([[[0,0,0],[0,0,0]],[[0,0,0],[0,0,0]],[[0,0,0],[0,0,0]],[[0,0,0],[0,0,0]]])
print(arr3d)
arr3d.ndim

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]


3

In [41]:
#Problem 4 : Create 4D array  with dimention (5,4,2,3)
arr4d=np.array([[[[0,0,0],[0,0,0]],[[0,0,0],[0,0,0]],[[0,0,0],[0,0,0]],[[0,0,0],[0,0,0]]],[[[0,0,0],[0,0,0]],[[0,0,0],[0,0,0]],[[0,0,0],[0,0,0]],[[0,0,0],[0,0,0]]],[[[0,0,0],[0,0,0]],[[0,0,0],[0,0,0]],[[0,0,0],[0,0,0]],[[0,0,0],[0,0,0]]],[[[0,0,0],[0,0,0]],[[0,0,0],[0,0,0]],[[0,0,0],[0,0,0]],[[0,0,0],[0,0,0]]],[[[0,0,0],[0,0,0]],[[0,0,0],[0,0,0]],[[0,0,0],[0,0,0]],[[0,0,0],[0,0,0]]]])
print(arr4d)
arr4d.shape

[[[[0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]]]


 [[[0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]]]


 [[[0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]]]


 [[[0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]]]


 [[[0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]]]]


(5, 4, 2, 3)

# Accessing and Modifying Elements


In [33]:
#Problem 4: Given the following array, access the element at the second row, third column:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[1,2])

6


In [34]:
#Problem 5: Change the value of the element at the first row, first column to 10 in the following array:
arr = np.array([[1, 2], [3, 4]])
arr[0,0]=10
print(arr)

[[10  2]
 [ 3  4]]


# Reshaping Arrays

In [45]:
#Problem 6: Take a 1D array of 12 elements and reshape it into a 2D array with shape (3, 4).
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
reshaped_array=arr.reshape(3,4)
reshaped_array.shape


(3, 4)

In [49]:
#Problem 7: Create a 2D array of shape (2, 6) and reshape it to (3, 4). What error do you get? 
arr=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
reshaped_array=arr.reshape(3,4)
reshaped_array

# No error

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Array Dimensions and Properties


In [53]:
#Problem 8: Create a 2D array of shape (5, 5) and print its shape and number of dimensions.
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("Its shape is " , arr.shape)
print("It has ",arr.ndim,"dimentions")

Its shape is  (2, 5)
It has  2 dimentions


In [58]:
#Problem 9: Create a 3D array of shape (2, 3, 4) and find out the size of the first dimension.
arr=np.array([[[0,0,0,0],[0,0,0,0],[0,0,0,0]],[[0,0,0,0],[0,0,0,0],[0,0,0,0]]])
print("Its size is " , arr[0].shape)

Its size is  (3, 4)


# Stacking and Concatenation


In [69]:
#Problem 10: Create two 1D arrays of shape (3,) and concatenate them into a single 1D array.
arr1=np.array([[1,2,3],[2,4,5]])
arr2=np.array([[4,5,6],[7,8,9]])
Concat_arr=np.concatenate((arr1,arr2), axis=0)
print("Concated array is : ",Concat_arr)

Concated array is :  [[1 2 3]
 [2 4 5]
 [4 5 6]
 [7 8 9]]


In [74]:
#Problem 11: Create two 2D arrays of shape (2, 3) and stack them vertically.
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
vstack_arr=np.vstack((arr1,arr2))
print(vstack_arr)
# Now practice hstack
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
hstack_arr=np.hstack((arr1,arr2))
print(hstack_arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


#  Slicing and Indexing


In [75]:
#Problem 12: Given the following array, extract the last row:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("Last Row is :  ",arr[2])

Last Row is :   [70 80 90]


In [83]:
# Problem 13: From a 2D array of shape (4, 4), select all elements from the first two rows and last two columns.
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
arr=arr.reshape(4,4)
print(arr[:2,:])
print(arr[:,-2:])


[[1 2 3 4]
 [5 6 7 8]]
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]


#  Advanced Indexing


In [86]:
#Problem 14: Create a 2D array and use boolean indexing to select all elements greater than 5. 
arr=np.array([1,2,3,4,5,6,7,8,9,10]) 
condition=arr>5 
modified_arr=arr[condition] 
print("Values greater then 5 are : ",modified_arr)

Values greater then 5 are :  [ 6  7  8  9 10]


In [88]:
#Problem 15: Create a 1D array with values from 1 to 10, and then index it using a list of indices [0, 2, 4, 6].
arr=np.array([1,2,3,4,5,6,7,8,9,10]) 
index_arr=[0, 2, 4, 6]
print("Array with given indexes is ",arr[index_arr])

Array with given indexes is  [1 3 5 7]


# Broadcasting

In [92]:
#Problem 16: Create a 2D array of shape (3, 4) and add a 1D array of shape (4,) to it.
TwoD_arr=np.random.rand(3,4)
OneD_arr=np.random.rand(4)
Updated_array=TwoD_arr + OneD_arr
print(Updated_array)

[[1.16434413 0.95516706 0.97477979 0.85148127]
 [1.55549007 1.52339432 1.67082162 0.99366029]
 [1.06828675 1.38768551 1.21333831 1.25467592]]


In [96]:
#Problem 17: Create two arrays of shape (2, 3) and (2, 1), and perform element-wise addition. What do you observe?
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7],[8]])
new_arr=arr1+arr2
print(new_arr)
#Yes it is adding each single element of second arr with whole arr in 1st array

[[ 8  9 10]
 [12 13 14]]


In [27]:
import numpy as np
arr1=np.array([4,5,6])
print(arr1.dtype)
print(type(arr1))
print(arr1.ndim)
print(arr1.shape)
print(arr1.itemsize)
print(arr1.nbytes)

int32
<class 'numpy.ndarray'>
1
(3,)
4
12


In [8]:
arr1=np.array([2,4,5,6])
arr2=np.array([2,4,5,6])
arr1*arr2

array([ 4, 16, 25, 36])

In [9]:
a=np.arange(11)

In [10]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
c = (2.0 * np.pi) / 10.0

In [12]:
c

0.6283185307179586

In [13]:
np.sin(c)

0.5877852522924731

In [16]:
arr1.fill(32.4)

In [17]:
arr1

array([32, 32, 32, 32])

In [20]:
a=np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
arr=np.arange(16)
arr=arr.reshape(2,4,2)
arr[1,3,0]

14

In [24]:
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [121]:
a1=np.arange(11)
a1=a1*np.pi*1e8
a1

array([0.0e+00, 3.1e+08, 6.3e+08, 9.4e+08, 1.3e+09, 1.6e+09, 1.9e+09,
       2.2e+09, 2.5e+09, 2.8e+09, 3.1e+09])

In [123]:
np.set_printoptions(precision=3)


In [124]:
a1

array([0.000e+00, 3.142e+08, 6.283e+08, 9.425e+08, 1.257e+09, 1.571e+09,
       1.885e+09, 2.199e+09, 2.513e+09, 2.827e+09, 3.142e+09])

In [125]:
np.set_printoptions(suppress=True)

In [126]:
a1

array([0.000e+00, 3.142e+08, 6.283e+08, 9.425e+08, 1.257e+09, 1.571e+09,
       1.885e+09, 2.199e+09, 2.513e+09, 2.827e+09, 3.142e+09])

In [75]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
a[-1:-4]

a[-1:-5:-1]

In [88]:
a=np.arange(25)
a=a.reshape(5,5)

In [89]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [131]:
a[3:,3:]

array([[18, 19],
       [23, 24]])

In [138]:
a[1::2,0:4:2]

array([[ 5,  7],
       [15, 17]])

In [142]:
a[4,[0,1,4]]

array([20, 21, 24])

In [146]:
a=np.array([1,2,3,4,5])
b=a[2:4]
b[0]=10
np.shares_memory(a,b)

True

In [147]:
a

array([ 1,  2, 10,  4,  5])