In [3]:
import numpy as np

### Basic Array Creation

# Creatation of List
create List in python? # Check Type of list

In [2]:
# Code here
list1=[1,2,3,4,5]
print(list1)

[1, 2, 3, 4, 5]


# Creatation of Arrays
1.Create an array containing 10 elements

2.Checking array "TYPE"

3.Check data type of array elements

4.Array dim

5.Array Shape

6.Bytes per element

7.Total bytes in an Array

In [7]:
# Create 'int' array and repeat above mention steps 1-7
# 1.Create an array containing 10 elements
arr1=np.arange(11)
print(arr1)
# 2.Checking array "TYPE"
print(type(arr1))
# 3.Check data type of array elements
print(arr1.dtype)
# 4.Array dim
print(arr1.ndim)
# 5.Array Shape
print(arr1.shape)
# 6.Bytes per element
print(arr1.itemsize)
# 7.Total bytes in an Array
print(arr1.nbytes)

[ 0  1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>
int64
1
(11,)
8
88


In [10]:
# Create 'float' array and repeat above mention steps 1-7
# 1.Create an array containing 10 elements
f_arr1=np.arange(11.0)
print(f_arr1)
# 2.Checking array "TYPE"
print(type(f_arr1))
# 3.Check data type of array elements
print(f_arr1.dtype)
# 4.Array dim
print(f_arr1.ndim)
# 5.Array Shape
print(f_arr1.shape)
# 6.Bytes per element
print(f_arr1.itemsize)
# 7.Total bytes in an Array
print(f_arr1.nbytes)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
<class 'numpy.ndarray'>
float64
1
(11,)
8
88


-Try to assign a float into an int32

-Use .fill function # fill has the same behavior


In [18]:
# -Try to assign a float into an int32
int_arr1=np.arange(11,dtype=np.int32)
print(int_arr1.dtype)
# Use .fill function
int_arr1.fill(1.0)
print(int_arr1)

int32
[1 1 1 1 1 1 1 1 1 1 1]


-. Add two  arrays

-. Multiple both arrays

-.Use ** operator in array operation

-.Create array from 0.0 to 11.0

-.Multiply entire array with a scalar value
 c = (2.0 * np.pi)

-.Use np.arrange function to create an array with step of 0.5 from 1.0 to 3.0

In [21]:
arr1=np.arange(5)
arr2=np.arange(5,10)
print(arr1)
print(arr2)
# -Add two  arrays
print(arr1+arr2)
# -Multiple both arrays
print(arr1*arr2)
# -Use ** operator in array operation
print(arr1**arr2)
# -.Multiply entire array with a scalar value c = (2.0 * np.pi)
c = (2.0 * np.pi)
print(c*arr1)
# -Use np.arrange function to create an array with step of 0.5 from 1.0 to 3.0
print(np.arange(1.0,3.0,0.5))

[0 1 2 3 4]
[5 6 7 8 9]
[ 5  7  9 11 13]
[ 0  6 14 24 36]
[     0      1    128   6561 262144]
[ 0.          6.28318531 12.56637061 18.84955592 25.13274123]
[1.  1.5 2.  2.5]


# Slicing
var[lower:upper:step]
• Extracts a portion of a sequence by specifying a lower and upper bound.

• The lower-bound element is included, but the upper-bound element is not included.

• Mathematically: [lower, upper). The step value specifies the stride between elements.

1. Etract array indices from 1 to 3:
2. Use negative indices as well
3. Omitted boundaries are assumed to be the beginning (or end) of the array grab first three elements
4. Grab last two elements
5. Grab every other element
6. slicing the last two elements returns the data there
7. Can we insert an iterable of length two? or a scalar value
8.Arrays created by slicing share data with the originating array. Changing values in a slice also changes the original array.
For example create a slice containing two elements of a changing b changed a! Have an experiment
9. if an array a = [[0,1,2,3,4][1,2,3,4,5], extract values from row 1 and col 0,2,4
10. Perform some masking on a = np.arange(0,36).reshape(6,6)
with mask = np.array([1, 0, 1, 0, 0, 1])


In [48]:
arr1=np.arange(11)
# Etract array indices from 1 to 3:
print(arr1[1:4])
# Use negative indices as well
print(arr1[-10:-7:1])
# Omitted boundaries are assumed to be the beginning (or end) of the array grab first three elements
print(arr1[:3])
# Grab last two elements
print(arr1[-2::])
# Grab every other element
print(arr1)
# slicing the last two elements returns the data there
print(arr1[-2::])
# Can we insert an iterable of length two? or a scalar value
arr1=np.arange(4)
arr1=np.append(arr1,[4,5])
print(arr1) #YES
#or a scalar value
arr1=np.arange(4)
arr1=np.append(arr1,6)
print(arr1)  #YES
# Arrays created by slicing share data with the originating array. Changing values in a slice also changes the original array. For example create a slice containing two elements of a changing b changed a! Have an experiment
arr1=np.arange(7)
b=arr1[2:4]
b[0]=10
print(arr1) # Yes it changes the main array
# if an array a = [[0,1,2,3,4][1,2,3,4,5], extract values from row 1 and col 0,2,4
a=np.array([[0,1,2,3,4],[1,2,3,4,5]])
print(a[1,[0,2,4]])
# Perform some masking on a = np.arange(0,36).reshape(6,6)
# with mask = np.array([1, 0, 1, 0, 0, 1])
a = np.arange(0,36).reshape(6,6)
mask = np.array([1, 0, 1, 0, 0, 1])
masked_arr=a[mask==1]
print(masked_arr)

[1 2 3]
[1 2 3]
[0 1 2]
[ 9 10]
[ 0  1  2  3  4  5  6  7  8  9 10]
[ 9 10]
[0 1 2 3 4 5]
[0 1 2 3 6]
[ 0  1 10  3  4  5  6]
[1 3 5]
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [30 31 32 33 34 35]]


In [3]:
import numpy as np
arr=np.random.randint(1,100,size=(5,6))
arr
row=[1,2,4]
col=[]

array([[13, 75, 28, 39,  5, 27],
       [82, 53, 43, 87,  7, 11],
       [45, 91, 89,  1, 35, 62],
       [92, 27, 68, 15, 74, 53],
       [12, 50, 58, 11,  3, 78]])

### Create a 2-D array where the first row goes from 10 to 80 exclusive with steps of 5 and 2nd row goes from 5 to 47 exclusive with steps of 3

In [50]:
arr=np.arange(10,80,5)
arr1=np.arange(5,47,3)
arr2=np.array([arr,arr1])
print(arr2)

[[10 15 20 25 30 35 40 45 50 55 60 65 70 75]
 [ 5  8 11 14 17 20 23 26 29 32 35 38 41 44]]


### Now use indexing to select the 5th 7th and 11th columns

In [51]:
#Code
arr2[:,[5,7,11]]

array([[35, 45, 65],
       [20, 26, 38]])

### Select the 2nd row and fourth-last to second-last columns

In [56]:
# Select the 2nd row and fourth-last to second-last columns
arr2[1,-4:-1:1]

array([35, 38, 41])

### Select 3rd to 3rd last columns skipping every second column

In [59]:
arr2[:,3:-2:2]

array([[25, 35, 45, 55, 65],
       [14, 20, 26, 32, 38]])

###  Select 3rd to 3rd last columns skipping every second column but in reverse order

In [60]:
arr2[:,-3:1:-2]

array([[65, 55, 45, 35, 25],
       [38, 32, 26, 20, 14]])

### Zip Operations on Numpy Arrays
Use a zip function on two arrys.

Create another array which would be the sum of corresponding elements of two arrays using for loop.

In [62]:
a = [1, 2, 3, 4]
b = [2, 3, 4, 5]
c=[]
for i,j in zip(a,b):
    c.append(i+j)
print(c)

[3, 5, 7, 9]


In [63]:
#For loop to add corresponding elements in two lists
c=[]
for i in range(len(a)):
    c.append(a[i]+b[i])
print(c)

[3, 5, 7, 9]
