# Problem 1: Reshaping for Image Processing
You are working on an image processing project, and you have a grayscale image represented as a 1D NumPy array **img_data** of size **(m * n)**, where m and n are the dimensions of the image. Write a function **reshape_image(img_data, new_shape)** that takes the original image data and a tuple representing the new shape **(p, q)** of the image. Ensure that the total number of pixels remains unchanged. If it's not possible to reshape without changing the total number of pixels, return **None**.

In [25]:
# Write your function in this cell
def reshape_image(data,shape):
    try:
        result=np.reshape(data,shape)
        return result
    except:
        retukrn None
#We can do same thing manually as well using this code : 
    # if len(data)!= shape[0]*shape[1]:
    #     return None
    # else:
    #     result=np.reshape(data,shape)
    #     return result

In [27]:
import numpy as np

img_data = np.arange(9)  # Assuming a 3x3 image
new_shape = (3, 3)
result = reshape_image(img_data, new_shape)
print(result)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Problem 2: Matrix Transpose
You are dealing with a dataset stored as a NumPy array **data_matrix** with dimensions **(m, n)**. Implement a function **transpose_matrix(data_matrix)** that returns the transpose of the given matrix.

In [30]:
# Write your function in this cell
def transpose_matrix(data):
    result=np.transpose(data)
    return result

In [32]:
import numpy as np

data_matrix = np.array([[1, 2, 3], [4, 5, 6]])

transposed_matrix = transpose_matrix(data_matrix)
print(transposed_matrix)

[[1 4]
 [2 5]
 [3 6]]


# Problem 3: Flattening for Data Processing
You have a 2D array representing data from different sensors. Write a function **flatten_sensor_data(sensor_data)** that takes a 2D NumPy array representing the sensor readings and returns a flattened 1D array.

In [43]:
# Write your function in this cell
def flatten_sensor_data(data):
    result=data.flatten()
    return result

In [45]:
import numpy as np

sensor_data = np.array([[10, 20, 30], [40, 50, 60]])
flattened_data = flatten_sensor_data(sensor_data)
print(flattened_data)

[10 20 30 40 50 60]
