In [1]:
import numpy as np

# Q1

Statement: Given a 3D NumPy array arr of shape (2, 3, 4), write a code snippet to calculate the sum of all elements in the array.

Sample Input:

In [4]:
arr=np.arange(24).reshape(2,3,4)
print(np.sum(arr))

276


# Q2



```
# This is formatted as code
```

Statement: Write a NumPy code snippet to create a 4D array arr of shape (2, 3, 4, 5) filled with random integers ranging from 0 to 9.

Sample Output:

In [8]:
# Answer Here
arr=np.random.randint(0,10,size=(2, 3, 4, 5))
arr

array([[[[3, 7, 9, 2, 1],
         [7, 5, 7, 5, 3],
         [7, 1, 4, 2, 9],
         [4, 6, 2, 5, 1]],

        [[4, 6, 6, 5, 2],
         [9, 8, 9, 7, 3],
         [1, 0, 0, 3, 3],
         [9, 6, 8, 2, 2]],

        [[6, 2, 0, 5, 2],
         [9, 2, 4, 7, 6],
         [3, 9, 4, 8, 2],
         [5, 4, 7, 2, 2]]],


       [[[6, 5, 2, 4, 7],
         [1, 7, 2, 7, 9],
         [1, 2, 1, 1, 6],
         [6, 3, 9, 1, 7]],

        [[9, 3, 9, 7, 1],
         [0, 2, 4, 1, 8],
         [9, 8, 8, 9, 7],
         [6, 9, 3, 5, 7]],

        [[3, 6, 4, 1, 6],
         [9, 7, 1, 7, 1],
         [0, 5, 8, 4, 8],
         [7, 2, 4, 6, 5]]]])

# Q3

Statement: Given a 4D NumPy array arr of shape (2, 3, 4, 5), write a code snippet to calculate the mean along the second axis.

Sample Input:

In [10]:
# Answer Here
arr=np.random.randint(0,10,size=(2, 3, 4, 5))
print(np.mean(arr,axis=1))

[[[3.         5.         2.33333333 6.         8.33333333]
  [3.         4.66666667 5.66666667 2.66666667 5.66666667]
  [4.33333333 5.66666667 3.         4.         3.33333333]
  [7.         3.66666667 4.33333333 3.         5.66666667]]

 [[4.33333333 3.33333333 1.         1.33333333 6.33333333]
  [2.         3.66666667 6.33333333 7.33333333 3.66666667]
  [3.         7.33333333 1.66666667 3.66666667 3.33333333]
  [7.         3.         4.         6.33333333 5.66666667]]]


# Q4

Statement: You have collected data from a temperature sensor placed at different locations over a period of time. The recorded temperatures are stored in a 3D NumPy array temps of shape (7, 24, 60), where the dimensions represent the number of days, hours in a day, and minutes in an hour, respectively. Write a code snippet to calculate the average temperature for each day.

Sample Input:

In [18]:
# Answer Here
arr=np.random.randint(30,42,size=(7,24,60))
avg_daily_mean=np.mean(arr,axis=(1,2))
print(avg_daily_mean)

[35.55208333 35.40416667 35.43819444 35.43472222 35.40416667 35.49861111
 35.47569444]


Sample Output:

array([27.43864059, 26.99643944, 27.10398301, 27.43854821, 26.81072977,
       26.76581481, 27.07946152])

# Q5

Statement: You have collected data from multiple sensors placed in different rooms of a building. The sensor readings are stored in a 4D NumPy array readings of shape (4, 7, 24, 60), where the dimensions represent the number of sensors, number of days, hours in a day, and minutes in an hour, respectively. Write a code snippet to calculate the maximum reading for each sensor across all days.

In [20]:
# Answer Here
# Answer Here
arr=np.random.randint(50,100,size=(4,7,24,60))
max_readings_per_sensor =np.mean(arr,axis=(1,2,3))
print(max_readings_per_sensor )

[74.49037698 74.55178571 74.44265873 74.72321429]


# Q6

Statement: You have collected data from a 3D printer that measures the dimensions of printed objects. The recorded dimensions are stored in a 3D NumPy array dimensions of shape (100, 50, 3), where the dimensions represent the number of printed objects, number of measurements for each object, and the three dimensions (length, width, height), respectively. Write a code snippet to calculate the average length, width, and height across all objects.

Sample Inpumt:

In [24]:
# Answer Here
arr=np.random.rand(100, 50, 3)
avg =np.mean(arr,axis=(0,1))
print("average length  of all objects",avg[0])
print("average width of all objects",avg[1])
print("average height of all objects",avg[2])


average length  of all objects 0.5061862582307812
average width of all objects 0.4927442970765481
average height of all objects 0.4935383472803382


# Q7

Statement: You are given a 3D NumPy array data of shape (5, 6, 7) representing the sensor readings from multiple sensors placed in different locations over a period of time. Each sensor provides measurements at different time points. Write a code snippet to calculate the following statistics for each sensor:

Total number of measurements

Average measurement value

Standard deviation of measurements

Minimum measurement value

Maximum measurement value

Sample Input:

In [37]:
# Answer Here
arr=np.random.rand(5, 6, 7)
print("Total number of measurements",arr.shape[1])
print("Average measurement value",np.mean(arr,axis=1))
print("Standard deviation of measurements",np.std(arr,axis=1))
print("Minimum measurement value",np.min(arr,axis=1))
print("Maximum measurement value",np.max(arr,axis=1))

Total number of measurements 6
Average measurement value [[0.56702565 0.49548725 0.43293888 0.37898257 0.47676208 0.50146956
  0.57155645]
 [0.58789044 0.58070455 0.563361   0.6503693  0.49460201 0.58501931
  0.56138527]
 [0.64976359 0.5393745  0.72235635 0.38134486 0.37122136 0.39501035
  0.34411608]
 [0.39561427 0.62334745 0.49009544 0.35756663 0.46384547 0.62008171
  0.66510026]
 [0.44085673 0.40810037 0.44227345 0.42100244 0.60837016 0.28151175
  0.41498029]]
Standard deviation of measurements [[0.31193409 0.28739075 0.26986195 0.28712562 0.33735583 0.28978852
  0.31155754]
 [0.21464102 0.21766647 0.26012039 0.17794309 0.28451569 0.14835883
  0.22824665]
 [0.22628046 0.20159394 0.35551232 0.249967   0.26379024 0.17790269
  0.36896412]
 [0.29805524 0.17079308 0.32789204 0.3108642  0.36987004 0.29348524
  0.35986997]
 [0.33301604 0.31009073 0.20226599 0.21061896 0.34442724 0.29325265
  0.23346137]]
Minimum measurement value [[0.20029198 0.13450848 0.12008432 0.05238438 0.00723533 0.1