# Numpy Basics Exercises

Please complete the following exercises **using numpy only**.

# Array Functions
1.Arange([start,] stop[, step],dtype=None)
Nearly identical to Python’s range(). Creates an array of values in the range [start,stop) with the specified step value. Allows non-integer values for start, stop, and step. Default dtype is derived from the start, stop, and step values. create an array with arange.

In [21]:
import numpy as np
arr=np.arange(10.0,30.0,3.5)
print(arr)
print(arr.dtype)



[10.  13.5 17.  20.5 24.  27.5]
float64


2.Create arrays with ONES, ZEROS, shape is a number or sequence specifying the dimensions of the array. If dtype is not specified, it defaults to float64.

In [6]:
arr1=np.ones((5,4),dtype=float)
print(arr1)
arr2=np.zeros((2,3),dtype=float)
print(arr2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]


3.Generate an n by n identity array. The default dtype is float64.

In [7]:
arr1=np.identity(5,dtype=float)
print(arr1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


4.use empty, full, and fill, max, min, std, mean, var, argmax, linspace

In [31]:
print(np.empty((5,4),dtype=float))
print(np.full((3,4),5.0))
print(arr.fill(5.0))
print(np.max(arr))
print(np.std(arr))
print(np.mean(arr))
print(np.var(arr))
print(np.argmax(arr))
print(np.linspace(1,8,10))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]
None
5.0
0.0
5.0
0.0
0
[1.         1.77777778 2.55555556 3.33333333 4.11111111 4.88888889
 5.66666667 6.44444444 7.22222222 8.        ]



5. Create the array below with a = np.arange(-15, 15).reshape(5, 6) ** 2

  Rule 1:
  Operations between multiple array objects are first checked for proper shape match.

  Rule 2:
  Mathematical operators (+ - * / exp, log, ...) apply element by element, on the values.

  Rule 3:
  Reduction operations (mean, std, skew, kurt, sum, prod, ...) apply to the whole array, unless an axis is specified.

  Rule 4:
  Missing values propagate unless explicitly ignored (nanmean, nansum, ...).

In [50]:
# code here and try to figure out different functions on your own (as stated in Rule 3, also figure out how to propogate missing values as stated in Rule 4)
from scipy.stats import kurtosis, skew
a = np.arange(-15, 15).reshape(5, 6) ** 2
print(np.sum(a))
print(a.sum())
print(a.prod())
print(np.std(a,axis=0))
print(np.mean(a,axis=0))
print(skew(a))
print(kurtosis(a))


2255
2255
0
[78.87204828 69.1433294  62.58434309 60.23952191 62.58434309 69.1433294 ]
[81. 76. 73. 72. 73. 76.]
[0.91287093 0.69630113 0.40604029 0.25612042 0.40604029 0.69630113]
[-0.5        -0.83386558 -1.39965398 -1.7244898  -1.39965398 -0.83386558]


6.Create the array below with
                  a = np.arange(-15, 15).reshape(5, 6) ** 2
1. The maximum of each row
2. The mean of each column
3. The position of the overall minimum

In [67]:
# code here and display all 3 values appropriately. You MUST NOT choose an array of your own choice.
a = np.arange(-15, 15).reshape(5, 6) ** 2
# The maximum of each row
print([np.max(i) for i in a])
# The mean of each column
print([np.mean(i) for i in np.transpose(a)])
# The position of the overall minimum
print(np.argmin(a))

[225, 81, 9, 64, 196]
[81.0, 76.0, 73.0, 72.0, 73.0, 76.0]
15


# Array Broadcasting
NumPy arrays of different dimensionality can be combined in the same expression. Arrays with smaller dimension are broadcasted to match the larger arrays, without copying data.

Broadcasting has two rules.

RULE 1: PREPEND ONES TO SMALLER ARRAY'S SHAPE

RULE 2: DIMENSIONS OF SIZE 1 ARE REPEATED WITHOUT COPYING

In [79]:
#code here # Create 2 arrays A and B with dim (5,4) and (5,) respectively, apply addition and subtraction.
a=np.arange(20).reshape(5,4)
b=np.arange(4)
print(a[:, np.newaxis]+b)
print(a[:, np.newaxis]-b)

[[[ 0  2  4  6]]

 [[ 4  6  8 10]]

 [[ 8 10 12 14]]

 [[12 14 16 18]]

 [[16 18 20 22]]]
[[[ 0  0  0  0]]

 [[ 4  4  4  4]]

 [[ 8  8  8  8]]

 [[12 12 12 12]]

 [[16 16 16 16]]]


1.Use reduce() operation on an array to reduec it into a single meaningful value. You. can also use a specific axis to apply reduce operation.

2.accumulate() creates a new array containing the intermediate results of the reduce operation at each element in a.


In [137]:
# Answer here (use both of these functions on an array of your own choice)
x=np.array([1,2,3,4,5])
x1=np.add.reduce(x)
print(x1)
x2=np.add.accumulate(x)
print(x2)

15
[ 1  3  6 10 15]


### We will work with the following array:

In [116]:
a = np.arange(25).reshape(5, 5)
a
#moving forward, you must use this array for the operations

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# Use slicing only to select 3rd and last row along with 2nd and last columns

In [87]:
# Answer here
print(a[2::2,(1,-1)])

[[11 14]
 [21 24]]


# Extract the following sub-array: [[2, 3], [12, 13], [22, 23]]

In [90]:
# Answer here
print(a[::2,(2,3)])

[[ 2  3]
 [12 13]
 [22 23]]


# Combine fancy/location indexing with slicing to extract the following sub-array: [[6, 8], [16, 18], [21, 23]]

In [104]:
# Answer here
row=[1,3,4]
col=[1,3]
print(a[row,:][:,col])
a

[[ 6  8]
 [16 18]
 [21 23]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# Change the values 1, 10, 19 and 22 in the array to -2

In [105]:
# Answer
val=[1,10,19,22]
a[0,1]=-2
a[2,0]=-2
a[3,-1]=-2
a[-1:1]=-2

# Repeat above using boolean indexing

In [114]:
# Answer here
b=[1,10,19,22]
condition= (a==1) | (a==10) | (a==19) | (a==22)
a[condition]=-2
print(a)

[[ 0 -2  2  3  4]
 [ 5  6  7  8  9]
 [-2 11 12 13 14]
 [15 16 17 18 -2]
 [20 21  2 23 24]]


# Combine slicing in the column dimension and boolean indexing in row dimension to extract the following sub-array: [[0, 3], [10, 13], [15, 18]]

In [119]:
# Answer here
row=np.array([True, False,True,True,False])
colums=[0,3]
print(a[row,:][:,colums])

[[ 0  3]
 [10 13]
 [15 18]]


# Calculating the sum, min and max of all diagonal values

In [122]:
# Answer here
diag=np.diagonal(a)
print(np.sum(diag))
print(np.min(diag))
print(np.max(diag))

60
0
24


# Calculate the sum of differences between the 2nd row and 2nd last column

In [123]:
# Answer here
row=a[1,:]
col=a[:,-2]
dif=row-col
print(np.sum(dif))

-30


# Create a new array that is the sum of even rows and odd rows

In [2]:
# Answer here
erow=a[0::2]
orow=a[1::2]
arr=[]
arr.append(np.sum(erow))
arr.append(np.sum(orow))
print(arr)

NameError: name 'a' is not defined

In [28]:
import numpy as np 
arr=np.random(100)
print(arr)

26


## You are done. Good job!