In [1]:
#import the required libraries
import numpy as np 
import pandas as pd

# Step 1 : Read the Data!

In [3]:
#give path of the source-file and store that path in a variable named census
census="makeSenseOfCensus.csv"

# Loading the data

You have studied getfromtext in Numpy Classes, now is the time to put it into action :) Below is the half completed code, you have to substitute values for delimiter and skip_header in it for hte data to be properly read into a Data array. The output of the array has been shared with you guys followed by the code block

In [6]:
data = np.genfromtxt(census, delimiter ="," , skip_header =1 )
print("\nData:\n\n ", data)


Data:

  [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


# Printing the type of data

In [8]:
#print the type of data
print(type(data))

<class 'numpy.ndarray'>


# Step 2 : Append the Data

A new record [[50,9,4,1,0,0,40,0]] has been given to you. You are supposed to append this new record into the data using np.concatenate()

## Append 'new_record' (given) to 'data' using "np.concatenate()"

In [12]:
new_record = [[50,9,4,1,0,0,40,0]]
new_data=np.concatenate((data,new_record))


In [13]:
#display after appending the new record at the end of the array.
new_data[-1]

array([50.,  9.,  4.,  1.,  0.,  0., 40.,  0.])

# Step 3 : Check if it's a young country or old country

 Create a new array called 'age' by taking only age column(age is the column with index 0) of 'census' array.

In [16]:
age=data[:,0]

Find the max age and store it in a variable called 'max_age'.



In [18]:
#print the max_age
# max_age=np.max(age,axis=0)/
max_age=age.max()
print("Maximum age is ",max_age,"years")

Maximum age is  90.0 years


Find the min age and store it in a variable called 'min_age'.

Find the min age and store it in a variable called 'min_age'.

In [21]:
#print the min_age
min_age=np.min(age)
print("Minimum age is ",min_age,"years")

Minimum age is  17.0 years


Find the mean of the age and store it in a variable called 'age_mean'.

In [23]:
#print the age_mean
age_mean=np.mean(age)
print("Average age is",age_mean,"year")

Average age is 38.051 year


Find the standard deviation of the age and store it in a variable called 'age_std'

In [25]:
#print the age_std
age_std=np.std(age)
print("Standard deviation of age is ",age_std)

Standard deviation of age is  13.342803266180612


# Step 4: Let's check the country's race distribution to identify the minorities

Create four different arrays by subsetting 'census' array by Race column(Race is the column with index 2) and save them in 'race_0','race_1', 'race_2', 'race_3' and 'race_4' respectively(Meaning: Store the array where 'race'column has value 0 in 'race_0', so on and so forth)

In [28]:
race=data[:,2]
race_0=race[(race==0)]
race_1=race[(race==1)]
race_2=race[(race==2)]
race_3=race[(race==3)]
race_4=race[(race==4)]

Store the length of the above created arrays in 'len_0', 'len_1','len_2', 'len_3' and 'len_4' respectively

In [30]:
#len_0
Len_0=len(race_0)
Len_0

10

In [31]:
#len_1
Len_1=len(race_1)
Len_1

27

In [32]:
#len_2
Len_2=len(race_2)
Len_2

110

In [33]:
#len_3
Len_3=len(race_3)
Len_3

6

In [34]:
#len_4
Len_4=len(race_4)
Len_4

847

Find out which is the race with the minimum no. of citizens

In [36]:
race1,count=np.unique(race,return_counts=True)
min_count=np.argmin(count)
print("Race with minimum citizen is race",race1[min_count])

Race with minimum citizen is race 3.0


Find out which is the race with the minimum no. of citizens

In [38]:
race2,count=np.unique(race,return_counts=True)
max_count=np.argmax(count)
print("Race with maximum citizen is race",race2[max_count])

Race with maximum citizen is race 4.0


Store the number associated with the minority race in a variable called 'minority_race'(For eg: if "len(race_5)" is the minimum, store 5 in 'minority_race' because that is the index of the race having the least no. of citizens )

In [52]:
lenarr=[Len_0,Len_1,Len_2,Len_3,Len_4]
minority_race=np.min(lenarr)
minority_race

6

Store the number associated with the minority race in a variable called 'minority_race'(For eg: if "len(race_5)" is the minimum, store 5 in 'minority_race' because that is the index of the race having the least no. of citizens )

In [54]:
lenarr=[Len_0,Len_1,Len_2,Len_3,Len_4]
majority_race=np.max(lenarr)
majority_race

847

# Step 5: As per govt. records citizens above 60 should not work more than 25 hours a week. Let us check if the policy is in place

a.Create a new subset array called 'senior_citizens' by filtering 'census' according to age>60 (age is the column with index 0)

[Row,Columns]  :

In [64]:
#from age column, filter out age data > 60
senior_citizens=data[(data[:,0]>60) & (data[:,-2]<25)]
senior_citizens

array([[7.900e+01, 1.000e+01, 4.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
        2.000e+01, 0.000e+00],
       [6.700e+01, 6.000e+00, 4.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
        2.000e+00, 0.000e+00],
       [7.100e+01, 1.000e+01, 2.000e+00, 1.000e+00, 0.000e+00, 1.816e+03,
        2.000e+00, 0.000e+00],
       [6.800e+01, 2.000e+00, 4.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        2.000e+01, 0.000e+00],
       [6.600e+01, 1.100e+01, 4.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        2.000e+01, 0.000e+00],
       [7.500e+01, 1.100e+01, 4.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        2.000e+01, 0.000e+00],
       [6.500e+01, 9.000e+00, 4.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
        1.600e+01, 0.000e+00],
       [6.200e+01, 9.000e+00, 4.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        2.400e+01, 0.000e+00],
       [7.600e+01, 1.400e+01, 4.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
        1.000e+01, 0.000e+00],
       [6.700e+01, 7.000e+00, 4.000e+00, 1.000e+00, 0.0

b.Add all the working hours(working hours is the column with index 6) of 'senior_citizens' and store it in a variable called 'working_hours_sum'

In [70]:
working_hours_sum=senior_citizens[:,6].sum()
working_hours_sum

367.0

c.Find the length of 'senior_citizens' and store it in a variable called 'senior_citizens_len'

In [74]:
senior_citizens_len=len(senior_citizens)
senior_citizens_len

24

d. Finally find the average working hours of the senior citizens by dividing 'working_hours_sum' by 'senior_citizens_len' and store it in a variable called 'avg_working hours'.

In [76]:
avg_working_hours=working_hours_sum/senior_citizens_len
avg_working_hours

15.291666666666666

e. Print 'avg_working_hours' and see if the govt. policy is followed.

In [82]:
print("Average working hours are",avg_working_hours)
if avg_working_hours>25:
    print("Policy Not followed")
else:
    print("Policy followed")

Average working hours are 15.291666666666666
Policy followed


# Step 6: Let's check that higher educated people have better pay in general.

Create two new subset arrays called 'high' and 'low' by filtering 'census' according to education-num>10 and education-num<=10 (education-num is the column with index 1) respectively.



In [108]:



high=data[(data[:,1]>10)]
low=data[data[:,1]<10]

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [28., 13.,  2., ...,  0., 40.,  0.],
       ...,
       [45., 14.,  4., ...,  0., 45.,  0.],
       [48., 13.,  4., ...,  0., 58.,  1.],
       [39., 13.,  4., ...,  0., 50.,  1.]])

Find the mean of income column(income is the column with index 7) of 'high' array and store it in 'avg_pay_high'. Do the same for 'low' array and store it's mean in 'avg_pay_low'.

In [112]:
avg_pay_high=np.mean(high[7])
avg_pay_low=np.mean(low[7])

In [114]:
avg_pay_high

8.75

In [116]:
avg_pay_low

12.5